"""Los 100 Primales inspirados en Ecuador (fuente original del catálogo).

Genera assets/criaturas/criaturas.json, que es la ficha de cada criatura (datos de juego + arte).
Después, scripts/construir_especies.py convierte esa ficha en shared/src/especies.ts.

Columnas: id, nombre, tipos, etapa, evoluciona_a, rareza, perfil, basico, habilidad, talla, visual, desc_es, desc_en
"""
import json
import os
import random

R = [
    # ---- comunes: líneas de 3 (las primeras de cada una se pueden elegir al empezar)
    ('tunguri', 'Tunguri', 'fuego', 1, 'tungurak', 'comun', 'rapido', 'cuerpo', 'brasa_interior', 'pequeño',
     'small cute orange salamander creature with a tiny smoking volcano cone on its back and glowing ember spots',
     'Salamandra nacida en las faldas del Tungurahua. El cráter de su lomo humea cuando se emociona.',
     'A salamander born on the slopes of Tungurahua. The tiny crater on its back smokes when it gets excited.'),
    ('tungurak', 'Tungurak', 'fuego', 2, 'tungurex', 'comun', 'fuerte', 'cuerpo', 'brasa_interior', 'mediano',
     'bipedal red lizard warrior creature with a volcano-shaped crest spewing small flames, dark ash-gray scales with glowing lava cracks',
     'Escupe ceniza cuando se enfada. Sus pasos dejan brasas encendidas.',
     'It spits ash when angry. Its footsteps leave glowing embers.'),
    ('tungurex', 'Tungurex', 'fuego/roca', 3, None, 'comun', 'robusto', 'cuerpo', 'brasa_interior', 'grande',
     'huge fierce volcano dinosaur creature with an erupting volcano crater on its back, black basalt armor plates and rivers of glowing lava',
     'Rey de los volcanes andinos. Cuando ruge, la tierra entera retumba.',
     'King of the Andean volcanoes. When it roars, the whole land rumbles.'),
    ('yakupi', 'Yakupi', 'agua', 1, 'yakulobo', 'comun', 'equilibrado', 'distancia', 'marea', 'pequeño',
     'small cute sea lion pup creature with big shiny eyes, light blue fur and a water droplet on its nose',
     'Cría de lobo marino de Galápagos. Juega con las olas todo el día.',
     'A Galápagos sea lion pup. It plays with the waves all day long.'),
    ('yakulobo', 'Yakulobo', 'agua', 2, 'yakuaron', 'comun', 'rapido', 'distancia', 'marea', 'mediano',
     'agile sea lion creature with a wave-shaped fin crest and swirling water around its flippers, deep blue fur',
     'Nada más rápido que una lancha. Dispara chorros con sus aletas.',
     'It swims faster than a speedboat and fires jets from its flippers.'),
    ('yakuaron', 'Yakuarón', 'agua/hielo', 3, None, 'comun', 'tanque', 'distancia', 'marea', 'grande',
     'massive walrus-like sea lion king creature with icy tusks, frost-covered blue fur and a crown of cold ocean waves',
     'Guardián de la fría corriente de Humboldt. Sus colmillos son de hielo eterno.',
     'Guardian of the cold Humboldt Current. Its tusks are made of everlasting ice.'),
    ('cacaito', 'Cacaíto', 'planta', 1, 'cacaoso', 'comun', 'tanque', 'cuerpo', 'espesura', 'pequeño',
     'small cute round creature shaped like a yellow cacao pod with a leafy sprout on top, tiny legs and a cheerful face',
     'Nace de una mazorca de cacao fino de aroma. Huele a chocolate.',
     'Born from a fine-aroma cacao pod. It smells like chocolate.'),
    ('cacaoso', 'Cacaoso', 'planta', 2, 'cacaotor', 'comun', 'robusto', 'cuerpo', 'espesura', 'mediano',
     'sturdy bipedal cacao pod creature with orange-brown husk armor, vine arms and big leaves on its shoulders',
     'Protege las plantaciones de la costa. Lanza semillas amargas.',
     'It protects the coastal plantations and hurls bitter seeds.'),
    ('cacaotor', 'Cacaotor', 'planta/sombra', 3, None, 'comun', 'fuerte', 'cuerpo', 'espesura', 'grande',
     'large powerful dark chocolate golem beast made of cacao pods and twisted roots, with glowing purple eyes and leaf horns',
     'Su cuerpo es de cacao negro. Dicen que un bocado da fuerzas para todo un día.',
     'Its body is made of dark cacao. They say one bite gives strength for a whole day.'),
    ('chispez', 'Chispez', 'electrico', 1, 'anguilampo', 'comun', 'rapido', 'distancia', 'estatica', 'pequeño',
     'small cute electric eel fish creature with yellow lightning stripes, round head and a sparking tail',
     'Pececito del Amazonas que chispea al reír.',
     'A little Amazon fish that sparks when it laughs.'),
    ('anguilampo', 'Anguilampo', 'electrico', 2, 'voltanguila', 'comun', 'rapido', 'distancia', 'estatica', 'mediano',
     'long electric eel creature floating in the air, dark green body with glowing yellow electric organs and lightning whiskers',
     'Ilumina los ríos de noche. Su descarga ahuyenta a cualquier depredador.',
     'It lights up the rivers at night. Its shock scares off any predator.'),
    ('voltanguila', 'Voltanguila', 'electrico/agua', 3, None, 'comun', 'fuerte', 'distancia', 'estatica', 'grande',
     'huge serpent-like electric eel dragon with thunder clouds around it, glowing yellow and teal stripes and a crackling lightning crest',
     'Señora de las tormentas del río Napo. Su rugido suena a trueno.',
     'Mistress of the Napo River storms. Its roar sounds like thunder.'),
    ('quindito', 'Quindito', 'viento', 1, 'quindazo', 'comun', 'rapido', 'distancia', 'viento_cola', 'pequeño',
     'tiny cute hummingbird creature with emerald green feathers, a long thin beak and blurry fast wings',
     'Los quindes son los colibríes de Ecuador. Este nunca deja de zumbar.',
     "Quindes are Ecuador's hummingbirds. This one never stops buzzing."),
    ('quindazo', 'Quindazo', 'viento', 2, 'quindestral', 'comun', 'rapido', 'distancia', 'viento_cola', 'mediano',
     'fierce hummingbird warrior creature with iridescent purple and green feathers, a sword-like beak and long tail streamers',
     'Su pico es tan afilado como una espada. Vuela hacia atrás para esquivar.',
     'Its beak is as sharp as a sword. It flies backwards to dodge.'),
    ('quindestral', 'Quindestral', 'viento/luz', 3, None, 'comun', 'asesino', 'distancia', 'viento_cola', 'grande',
     'majestic giant hummingbird creature with glowing golden and emerald plumage, star-shaped tail feathers and radiant light wings',
     'Inspirado en la estrella del Chimborazo, un colibrí andino. Sus alas dejan estelas de luz.',
     'Inspired by the Chimborazo hillstar, an Andean hummingbird. Its wings leave trails of light.'),
    ('galapito', 'Galapito', 'roca', 1, 'galapon', 'comun', 'tanque', 'cuerpo', 'roca_solida', 'pequeño',
     'small cute baby giant tortoise creature with a rocky saddle-shaped shell and a sleepy face',
     'Tortuguita de Galápagos. Puede dormir cien años seguidos.',
     'A tiny Galápagos tortoise. It can sleep for a hundred years straight.'),
    ('galapon', 'Galapón', 'roca', 2, 'galapagon', 'comun', 'tanque', 'cuerpo', 'roca_solida', 'mediano',
     'sturdy giant tortoise creature with a boulder shell covered in moss and small cactus, strong stony legs',
     'Su caparazón resiste una avalancha. Camina lento pero nunca se detiene.',
     'Its shell withstands an avalanche. It walks slowly but never stops.'),
    ('galapagon', 'Galapagón', 'roca/agua', 3, None, 'comun', 'tanque', 'cuerpo', 'roca_solida', 'grande',
     'colossal ancient giant tortoise creature with a volcanic island on its shell, small waterfalls and palm trees growing on its back',
     'Tan grande que en su caparazón crecen islas. Es el abuelo del archipiélago.',
     'So big that islands grow on its shell. It is the grandfather of the archipelago.'),
    ('chusik', 'Chusik', 'sombra', 1, 'chusikar', 'comun', 'equilibrado', 'distancia', 'sombra_esquiva', 'pequeño',
     'small cute round owl chick creature with dark purple feathers and huge glowing yellow eyes',
     'Chusik significa lechuza en kichwa. Sus ojos ven en la oscuridad total.',
     'Chusik means owl in Kichwa. Its eyes see in total darkness.'),
    ('chusikar', 'Chusikar', 'sombra', 2, 'chusikron', 'comun', 'asesino', 'distancia', 'sombra_esquiva', 'mediano',
     'sleek shadow owl creature with midnight blue feathers, sharp claws and a mysterious smoky aura',
     'Caza sin hacer ruido. Dicen que trae mensajes de la noche.',
     'It hunts without a sound. They say it carries messages from the night.'),
    ('chusikron', 'Chusikrón', 'sombra/viento', 3, None, 'comun', 'asesino', 'distancia', 'sombra_esquiva', 'grande',
     'large majestic dark owl lord creature with wings made of starry night sky and a glowing crescent moon on its forehead',
     'Cuando abre sus alas, el día se vuelve noche.',
     'When it opens its wings, day turns into night.'),
    ('ukumarito', 'Ukumarito', 'hielo', 1, 'ukumari', 'comun', 'robusto', 'cuerpo', 'corazon_glaciar', 'pequeño',
     'small cute spectacled bear cub creature with dark fur, cream spectacle markings around the eyes and frost on its ears',
     'Cría de oso de anteojos del páramo. Le encanta la nieve.',
     'A spectacled bear cub from the páramo. It loves snow.'),
    ('ukumari', 'Ukumari', 'hielo', 2, 'ukumarasu', 'comun', 'robusto', 'cuerpo', 'corazon_glaciar', 'mediano',
     'strong spectacled bear creature with icy blue-tinted fur, frosty spectacle markings and ice crystal claws',
     'Ukumari es el oso de las leyendas andinas. Sus garras congelan lo que tocan.',
     'Ukumari is the bear of Andean legends. Its claws freeze whatever they touch.'),
    ('ukumarasu', 'Ukumarasu', 'hielo/roca', 3, None, 'comun', 'tanque', 'cuerpo', 'corazon_glaciar', 'grande',
     'huge glacier bear creature with a back covered in ice crystals and snowy mountain peaks, glowing pale blue spectacle markings',
     'Duerme bajo los glaciares. Su despertar provoca avalanchas.',
     'It sleeps beneath the glaciers. Its awakening triggers avalanches.'),
    ('morfito', 'Morfito', 'luz', 1, 'crisalux', 'comun', 'equilibrado', 'distancia', 'aurora', 'pequeño',
     'small cute fuzzy caterpillar creature with glowing blue spots and tiny antennae tipped with light bulbs',
     'Oruga amazónica que brilla en la oscuridad.',
     'An Amazonian caterpillar that glows in the dark.'),
    ('crisalux', 'Crisalux', 'luz', 2, 'morfolux', 'comun', 'tanque', 'distancia', 'aurora', 'mediano',
     'glowing crystal chrysalis creature floating in the air, golden shell with light shining through cracks and two small eyes',
     'Dentro de su crisálida guarda la luz del sol.',
     'Inside its chrysalis it keeps the light of the sun.'),
    ('morfolux', 'Morfolux', 'luz/viento', 3, None, 'comun', 'rapido', 'distancia', 'aurora', 'grande',
     'magnificent giant blue morpho butterfly creature with shimmering electric-blue wings radiating light and an elegant body',
     'La mariposa morfo azul más grande del Amazonas. Sus alas deslumbran.',
     'The largest blue morpho of the Amazon. Its wings are dazzling.'),
    # ---- comunes: líneas de 2
    ('llamin', 'Llamín', 'fuego', 1, 'llamaradon', 'comun', 'equilibrado', 'distancia', 'brasa_interior', 'pequeño',
     'small cute fluffy baby llama creature with a little flame on its fluffy head tuft and colorful Andean tassels on its ears',
     'Una llamita con llama. Su lana siempre está calentita.',
     'A little llama with a flame. Its wool is always warm.'),
    ('llamaradon', 'Llamaradón', 'fuego/viento', 2, None, 'comun', 'rapido', 'distancia', 'brasa_interior', 'mediano',
     'proud adult llama creature with a blazing fire mane, a colorful woven Andean blanket and hot wind swirling around its hooves',
     'Escupe fuego en vez de saliva. Corre por los Andes como el viento.',
     'It spits fire instead of saliva and runs across the Andes like the wind.'),
    ('dardin', 'Dardín', 'planta', 1, 'dardosa', 'comun', 'rapido', 'distancia', 'toxico', 'pequeño',
     'tiny cute poison dart frog creature, bright blue with black spots and a leaf on its head',
     'Ranita venenosa del bosque. Su color avisa: ¡no me toques!',
     "A tiny poison frog of the forest. Its colors warn: don't touch me!"),
    ('dardosa', 'Dardosa', 'planta/sombra', 2, None, 'comun', 'asesino', 'distancia', 'toxico', 'mediano',
     'sleek poison dart frog creature with a vivid red and black pattern, dripping purple venom and a leaf-shaped crest',
     'Su piel tiene suficiente veneno para dormir a un jaguar.',
     'Its skin has enough venom to put a jaguar to sleep.'),
    ('pinzin', 'Pinzín', 'agua', 1, 'pinzaglar', 'comun', 'tanque', 'cuerpo', 'roca_solida', 'pequeño',
     'small cute red mangrove crab creature with one big claw and a bubbly mouth',
     'Vive entre las raíces del manglar. Pellizca a quien se acerca.',
     'It lives among the mangrove roots and pinches anyone who gets close.'),
    ('pinzaglar', 'Pinzaglar', 'agua/roca', 2, None, 'comun', 'tanque', 'cuerpo', 'roca_solida', 'mediano',
     'large armored mangrove crab creature with a stone-like shell, mangrove roots growing on its back and two huge claws',
     'Sus pinzas parten troncos. Defiende el manglar como una fortaleza.',
     'Its claws split logs. It defends the mangrove like a fortress.'),
    ('piranin', 'Pirañín', 'agua', 1, 'piranazo', 'comun', 'asesino', 'cuerpo', 'instinto_cazador', 'pequeño',
     'small cute round piranha fish creature with a sharp-toothed grin, red belly and tiny fins, floating in the air',
     'Pequeño pero muy mordelón. Nunca anda solo.',
     'Small but very bitey. It never travels alone.'),
    ('piranazo', 'Pirañazo', 'agua/sombra', 2, None, 'comun', 'asesino', 'cuerpo', 'instinto_cazador', 'mediano',
     'fierce large piranha creature with dark scales, glowing red eyes, huge jaws full of teeth and shadowy fins',
     'Huele el miedo desde lejos. Su mordida atraviesa armaduras.',
     'It smells fear from afar. Its bite pierces armor.'),
    ('capibin', 'Capibín', 'agua', 1, 'capibaron', 'comun', 'tanque', 'cuerpo', 'fotosintesis', 'pequeño',
     'small cute chubby capybara creature with a lily pad on its head and a calm sleepy smile',
     'El Primal más tranquilo del río. Todos quieren ser su amigo.',
     'The calmest Primal in the river. Everyone wants to be its friend.'),
    ('capibaron', 'Capibarón', 'agua', 2, None, 'comun', 'tanque', 'cuerpo', 'fotosintesis', 'mediano',
     'big relaxed capybara creature wearing a crown of water lilies, with small birds resting on its back and a river splash',
     'Nada sin prisa y nunca pierde la calma. Hasta los pájaros descansan sobre él.',
     'It swims at its own pace and never loses its cool. Even birds rest on it.'),
    ('pelusin', 'Pelusín', 'sombra', 1, 'taranton', 'comun', 'equilibrado', 'cuerpo', 'toxico', 'pequeño',
     'small cute fuzzy tarantula creature with dark purple hair, many shiny eyes and tiny fangs',
     'Una tarántula peludita y tímida. Teje telarañas con forma de estrella.',
     'A shy fuzzy tarantula. It weaves star-shaped webs.'),
    ('taranton', 'Tarantón', 'sombra/roca', 2, None, 'comun', 'robusto', 'cuerpo', 'toxico', 'mediano',
     'large tarantula creature with rocky armored legs, dark violet fur and glowing purple fangs',
     'Vive en las cuevas de la Amazonía. Sus patas son duras como la piedra.',
     'It lives in Amazon caves. Its legs are as hard as stone.'),
    ('piquerito', 'Piquerito', 'viento', 1, 'patazul', 'comun', 'equilibrado', 'distancia', 'viento_cola', 'pequeño',
     'small cute seabird chick creature with fluffy white down and very big bright blue feet, blue-footed booby',
     'Presume sus patas azules. Baila para hacer amigos.',
     'It shows off its blue feet and dances to make friends.'),
    ('patazul', 'Patazul', 'viento/agua', 2, None, 'comun', 'rapido', 'distancia', 'viento_cola', 'mediano',
     'elegant blue-footed booby bird creature with wings spread, white and brown feathers and vivid turquoise feet',
     'Se lanza en picada al mar como una flecha. Su baile es famoso en Galápagos.',
     'It dives into the sea like an arrow. Its dance is famous in Galápagos.'),
    ('iguanin', 'Iguanín', 'fuego', 1, 'iguanarca', 'comun', 'robusto', 'cuerpo', 'brasa_interior', 'pequeño',
     'small cute yellow land iguana creature with a spiky orange crest and a warm glowing belly',
     'Toma el sol sobre rocas volcánicas hasta brillar.',
     'It sunbathes on volcanic rocks until it glows.'),
    ('iguanarca', 'Iguanarca', 'fuego/planta', 2, None, 'comun', 'robusto', 'cuerpo', 'brasa_interior', 'mediano',
     'large golden land iguana creature with a crest of flaming cactus spines and prickly pear cactus growing on its back',
     'Come cactus y respira fuego. Gobierna las islas secas.',
     'It eats cactus and breathes fire. It rules the dry islands.'),
    ('frailito', 'Frailito', 'planta', 1, 'frailejon', 'comun', 'tanque', 'cuerpo', 'fotosintesis', 'pequeño',
     'small cute fuzzy frailejon plant creature with a rosette of silvery hairy leaves on its head and tiny stubby legs',
     'Pequeña planta del páramo cubierta de pelusa para no tener frío.',
     'A small páramo plant covered in fuzz so it never gets cold.'),
    ('frailejon', 'Frailejón', 'planta/hielo', 2, None, 'comun', 'tanque', 'cuerpo', 'fotosintesis', 'mediano',
     'tall frailejon plant creature with a thick trunk body, a frosty silver leaf crown and yellow flowers, covered in morning frost',
     'Guardián del agua del páramo. Atrapa la niebla y la vuelve ríos.',
     "Guardian of the páramo's water. It catches the mist and turns it into rivers."),
    ('aullin', 'Aullín', 'electrico', 1, 'aullatrueno', 'comun', 'equilibrado', 'cuerpo', 'estatica', 'pequeño',
     'small cute howler monkey creature with reddish fur, a curly tail and tiny sparks around its open mouth',
     'Su grito se oye a kilómetros. Se carga de electricidad al gritar.',
     'Its howl can be heard for miles. Howling charges it with electricity.'),
    ('aullatrueno', 'Aullatrueno', 'electrico/viento', 2, None, 'comun', 'fuerte', 'cuerpo', 'estatica', 'mediano',
     'large howler monkey creature with storm cloud fur, lightning bolts in its mane and a long thunder tail',
     'Cuando aúlla, empieza a llover. Es el dueño de las copas de los árboles.',
     'When it howls, the rain begins. It owns the treetops.'),
    ('tucanin', 'Tucanín', 'viento', 1, 'tucanazo', 'comun', 'equilibrado', 'distancia', 'viento_cola', 'pequeño',
     'small cute toucan chick creature with a huge colorful orange beak and fluffy black and white feathers',
     'Su pico casi no pesa, aunque parezca enorme.',
     'Its beak weighs almost nothing, even though it looks huge.'),
    ('tucanazo', 'Tucanazo', 'viento/fuego', 2, None, 'comun', 'fuerte', 'distancia', 'concentracion', 'mediano',
     'large majestic toucan creature with a blazing rainbow beak glowing like fire and black feathers with flame-colored tips',
     'Su pico arde con los colores del atardecer amazónico.',
     'Its beak burns with the colors of the Amazon sunset.'),
    # ---- raros
    ('otoronguito', 'Otoronguito', 'sombra', 1, 'otorongo', 'raro', 'asesino', 'cuerpo', 'instinto_cazador', 'pequeño',
     'small cute black jaguar cub creature with faint rosette spots and glowing green eyes',
     'Cachorro de otorongo, el jaguar del Amazonas. Juega a cazar sombras.',
     'A cub of the otorongo, the Amazon jaguar. It plays at hunting shadows.'),
    ('otorongo', 'Otorongo', 'sombra/planta', 2, None, 'raro', 'asesino', 'cuerpo', 'instinto_cazador', 'grande',
     'powerful black jaguar creature with glowing jungle-green rosettes, vines wrapped around its legs and fierce eyes',
     'Rey de la selva. Aparece y desaparece entre las hojas.',
     'King of the jungle. It appears and vanishes among the leaves.'),
    ('amaruto', 'Amaruto', 'agua', 1, 'amarusacha', 'raro', 'equilibrado', 'cuerpo', 'marea', 'pequeño',
     'small cute young anaconda snake creature with green and black spotted scales, coiled up with a friendly face',
     'Amaru es la serpiente sagrada de los Andes. Esta todavía es pequeña.',
     'Amaru is the sacred serpent of the Andes. This one is still small.'),
    ('amarusacha', 'Amarusacha', 'agua/planta', 2, None, 'raro', 'tanque', 'cuerpo', 'marea', 'grande',
     'giant anaconda creature coiled in a river, mossy green scales with water lilies and jungle vines growing on its body',
     'La anaconda más grande del río. Sostiene la selva sobre su espalda.',
     'The largest anaconda in the river. It holds the jungle on its back.'),
    ('bufeito', 'Bufeíto', 'agua', 1, 'bufeorosa', 'raro', 'rapido', 'distancia', 'marea', 'pequeño',
     'small cute pink river dolphin creature with a long snout, playful smile and bubbles',
     'Delfín rosado del Amazonas. Le encanta hacer piruetas.',
     'A pink Amazon river dolphin. It loves doing flips.'),
    ('bufeorosa', 'Bufeorosa', 'agua/luz', 2, None, 'raro', 'equilibrado', 'distancia', 'aurora', 'grande',
     'elegant large pink river dolphin creature glowing with mystical light and sparkling water ribbons around it',
     'La leyenda dice que de noche se convierte en persona y va a las fiestas.',
     'Legend says that at night it turns into a person and goes to parties.'),
    ('harpin', 'Harpín', 'viento', 1, 'harpiandina', 'raro', 'fuerte', 'distancia', 'instinto_cazador', 'pequeño',
     'small cute fluffy harpy eagle chick creature with gray feathers and a double crest',
     'Pichón de águila harpía. Ya mira como un cazador.',
     "A harpy eagle chick. It already has a hunter's stare."),
    ('harpiandina', 'Harpiandina', 'viento/planta', 2, None, 'raro', 'fuerte', 'distancia', 'instinto_cazador', 'grande',
     'mighty harpy eagle creature with huge talons, gray and black feathers, a majestic double crest and leaves swirling in the wind',
     'El ave más fuerte del bosque. Sus garras son como garfios.',
     'The strongest bird of the forest. Its talons are like hooks.'),
    ('pingui', 'Pingüi', 'hielo', 1, 'galapingo', 'raro', 'rapido', 'distancia', 'corazon_glaciar', 'pequeño',
     'small cute Galapagos penguin chick creature, gray and fluffy with a white face stripe and icy blue flippers',
     'Uno de los pocos pingüinos que viven en la línea ecuatorial.',
     'One of the few penguins that live on the Equator.'),
    ('galapingo', 'Galapingo', 'hielo/agua', 2, None, 'raro', 'rapido', 'distancia', 'corazon_glaciar', 'mediano',
     'sleek penguin warrior creature sliding on ice, black and white with frost patterns and a cold water splash',
     'Patina sobre el mar y congela las olas a su paso.',
     'It skates over the sea, freezing the waves as it goes.'),
    ('martillin', 'Martillín', 'agua', 1, 'martillazo', 'raro', 'fuerte', 'cuerpo', 'instinto_cazador', 'pequeño',
     'small cute baby hammerhead shark creature with a wide hammer-shaped head and tiny fins, floating in the air',
     'Tiburón martillo bebé. Se golpea la cabeza con todo, pero no le duele.',
     "A baby hammerhead shark. It bumps its head on everything, but it doesn't hurt."),
    ('martillazo', 'Martillazo', 'agua/roca', 2, None, 'raro', 'fuerte', 'cuerpo', 'roca_solida', 'grande',
     'huge hammerhead shark creature with a stone-armored hammer head, gray-blue body and a powerful tail, ocean splashes',
     'Patrulla las aguas de Galápagos. Su cabeza parte rocas.',
     'It patrols the waters of Galápagos. Its head smashes rocks.'),
    ('atuk', 'Atuk', 'hielo', 1, 'atukrasu', 'raro', 'rapido', 'cuerpo', 'escarcha', 'pequeño',
     'small cute Andean fox kit creature with gray-red fur, a bushy tail with a frosty tip and big ears',
     'Atuk significa zorro en kichwa. Es travieso y muy listo.',
     'Atuk means fox in Kichwa. It is mischievous and very clever.'),
    ('atukrasu', 'Atukrasu', 'hielo/sombra', 2, None, 'raro', 'asesino', 'cuerpo', 'escarcha', 'mediano',
     'sleek páramo fox creature with frosty silver fur, dark shadowy tail tips and glowing icy eyes, snowflakes swirling',
     'El zorro fantasma del páramo. Deja huellas de escarcha.',
     'The ghost fox of the páramo. It leaves frosty footprints.'),
    ('pumita', 'Pumita', 'roca', 1, 'pumarumi', 'raro', 'asesino', 'cuerpo', 'instinto_cazador', 'pequeño',
     'small cute puma cub creature with tan fur, stone pebbles on its paws and curious eyes',
     'Cachorro de puma que juega entre las piedras.',
     'A puma cub that plays among the rocks.'),
    ('pumarumi', 'Pumarumi', 'roca/viento', 2, None, 'raro', 'asesino', 'cuerpo', 'instinto_cazador', 'grande',
     'powerful mountain puma creature with stone armor plates like Inca walls on its shoulders and wind swirling around its tail',
     'Rumi significa piedra. Su armadura recuerda a los muros incas.',
     'Rumi means stone. Its armor recalls the Inca walls.'),
    ('tapirin', 'Tapirín', 'planta', 1, 'tapiramo', 'raro', 'tanque', 'cuerpo', 'fotosintesis', 'pequeño',
     'small cute mountain tapir calf creature with striped and spotted fur, a short trunk and leaves on its back',
     'Cría de tapir de montaña. Sus rayas desaparecen al crecer.',
     'A mountain tapir calf. Its stripes fade as it grows.'),
    ('tapiramo', 'Tapiramo', 'planta/roca', 2, None, 'raro', 'tanque', 'cuerpo', 'fotosintesis', 'grande',
     'large woolly mountain tapir creature with mossy stone armor, a flexible trunk and ferns growing on its back',
     'Siembra el bosque nublado con cada paso.',
     'It plants the cloud forest with every step.'),
    ('vicunin', 'Vicuñín', 'hielo', 1, 'vicunieve', 'raro', 'rapido', 'distancia', 'viento_cola', 'pequeño',
     'small cute fluffy vicuna creature with golden wool, a long neck and a frosty white bib',
     'Su lana es la más fina del mundo.',
     'Its wool is the finest in the world.'),
    ('vicunieve', 'Vicuñieve', 'hielo/viento', 2, None, 'raro', 'rapido', 'distancia', 'escarcha', 'mediano',
     'graceful vicuna creature running, golden and white wool with ice crystals and a cold wind trailing behind it',
     'Corre por las faldas del Chimborazo a la velocidad del viento.',
     'It runs along the slopes of Chimborazo as fast as the wind.'),
    ('fragatin', 'Fragatín', 'viento', 1, 'fragatormenta', 'raro', 'rapido', 'distancia', 'viento_cola', 'pequeño',
     'small cute frigatebird chick creature with black feathers and a tiny red throat pouch',
     'Infla su buche rojo para presumir.',
     'It puffs up its red pouch to show off.'),
    ('fragatormenta', 'Fragatormenta', 'viento/electrico', 2, None, 'raro', 'rapido', 'distancia', 'furia_tormenta', 'grande',
     'large frigatebird creature with long sharp black wings crackling with lightning and a huge inflated glowing red pouch',
     'Roba la comida a otras aves en pleno vuelo, y también los rayos.',
     'It steals food from other birds in mid-flight, and lightning too.'),
    ('cuernin', 'Cuernín', 'roca', 1, 'hercularmor', 'raro', 'robusto', 'cuerpo', 'roca_solida', 'pequeño',
     'small cute beetle larva creature with a tiny horn, a brown shell and stubby legs',
     'Larva de escarabajo. Ya es fortísima.',
     'A beetle larva. It is already super strong.'),
    ('hercularmor', 'Hercularmor', 'roca/electrico', 2, None, 'raro', 'robusto', 'cuerpo', 'roca_solida', 'grande',
     'giant hercules beetle creature with a long shiny horn, metallic olive armor shell and electric sparks between its horn tips',
     'Levanta cien veces su peso. Su cuerno conduce la electricidad.',
     'It lifts a hundred times its weight. Its horn conducts electricity.'),
    ('cristalin', 'Cristalín', 'luz', 1, 'ranacristal', 'raro', 'equilibrado', 'distancia', 'aurora', 'pequeño',
     'small cute glass frog creature with transparent lime-green skin showing a glowing heart and big golden eyes',
     'Rana de cristal: se le ve el corazón brillar.',
     'A glass frog: you can see its heart glowing.'),
    ('ranacristal', 'Ranacristal', 'luz/agua', 2, None, 'raro', 'equilibrado', 'distancia', 'aurora', 'mediano',
     'elegant glass frog creature with a crystal-clear body refracting rainbow light, water droplets and a leaf perch',
     'Su cuerpo de cristal separa la luz como un prisma.',
     'Its crystal body splits light like a prism.'),
    ('caimancito', 'Caimancito', 'agua', 1, 'caimanegro', 'raro', 'robusto', 'cuerpo', 'instinto_cazador', 'pequeño',
     'small cute baby black caiman creature with dark scales, yellow eyes and a toothy smile',
     'Cría de caimán negro. Se esconde con solo los ojos fuera del agua.',
     'A black caiman hatchling. It hides with only its eyes above the water.'),
    ('caimanegro', 'Caimanegro', 'agua/sombra', 2, None, 'raro', 'robusto', 'cuerpo', 'instinto_cazador', 'grande',
     'huge black caiman creature with dark armored scales, glowing yellow eyes and shadowy swamp water around it',
     'El gran cazador de las lagunas amazónicas.',
     'The great hunter of the Amazon lagoons.'),
    # ---- épicos
    ('ayahuma', 'Aya Huma', 'sombra/fuego', 0, None, 'epico', 'fuerte', 'cuerpo', 'vampiro', 'grande',
     'fearsome Diablo Huma mask spirit creature with a two-faced colorful mask, horns, long colorful ribbons and a fiery dark aura, Andean festival dancer',
     'Espíritu del baile del Inti Raymi. Tiene dos caras: una mira al pasado y otra al futuro.',
     'The spirit of the Inti Raymi dance. It has two faces: one looks to the past, the other to the future.'),
    ('cotopaxin', 'Cotopaxín', 'fuego', 1, 'cotopaxor', 'epico', 'equilibrado', 'distancia', 'concentracion', 'mediano',
     'cute small volcano creature shaped like a perfect snow-capped cone with a glowing lava heart and little feet',
     'Un volcancito con gorro de nieve. Hierve por dentro.',
     'A little volcano wearing a snow cap. It boils inside.'),
    ('cotopaxor', 'Cotopaxor', 'fuego/hielo', 2, None, 'epico', 'robusto', 'distancia', 'concentracion', 'grande',
     'colossal volcano titan creature with a perfect snow-capped cone head erupting fire, lava rivers and glaciers on its body',
     'El volcán nevado más famoso cobra vida. Fuego y hielo en un solo cuerpo.',
     'The most famous snowy volcano comes to life. Fire and ice in a single body.'),
    ('quiloton', 'Quilotón', 'agua/sombra', 0, None, 'epico', 'tanque', 'distancia', 'marea', 'grande',
     'mysterious turquoise crater lake spirit creature, a round serpent coiled like a lagoon with an emerald water body and volcanic rim armor',
     'Duerme en el fondo de la laguna del Quilotoa. Su color cambia con el sol.',
     'It sleeps at the bottom of the Quilotoa lagoon. Its color changes with the sun.'),
    ('tunda', 'Tunda', 'sombra/planta', 0, None, 'epico', 'asesino', 'cuerpo', 'sombra_esquiva', 'grande',
     'eerie jungle forest spirit creature with a twisted wooden body, mossy hair, one leg like a tree root and glowing eyes',
     'Espíritu de las leyendas de Esmeraldas. Confunde a quien se pierde en el bosque.',
     'A spirit from the legends of Esmeraldas. It confuses anyone lost in the forest.'),
    ('gallofierro', 'Gallofierro', 'roca/luz', 0, None, 'epico', 'fuerte', 'cuerpo', 'roca_solida', 'mediano',
     'proud iron rooster creature made of wrought iron and gold, a weathervane tail and a glowing sunrise crest',
     'El gallo de hierro de la catedral de Cuenca. Cuando canta, sale el sol.',
     "The iron rooster of Cuenca's cathedral. When it crows, the sun rises."),
    ('iguamarina', 'Iguamarina', 'agua', 1, 'draconarina', 'epico', 'equilibrado', 'cuerpo', 'marea', 'mediano',
     'marine iguana creature with black spiky scales, a salty white crest and sea spray',
     'Iguana marina que estornuda sal. Bucea entre corales.',
     'A marine iguana that sneezes salt. It dives among corals.'),
    ('draconarina', 'Draconarina', 'agua/fuego', 2, None, 'epico', 'fuerte', 'cuerpo', 'marea', 'grande',
     'huge sea dragon iguana creature with black volcanic scales, a steaming red crest, ocean waves and fire around it',
     'Mitad dragón, mitad iguana marina. Hace hervir el mar.',
     'Half dragon, half marine iguana. It makes the sea boil.'),
    ('lumbron', 'Lumbrón', 'luz', 1, 'lumbrestrella', 'epico', 'equilibrado', 'distancia', 'aurora', 'mediano',
     'glowing firefly beetle creature with a big bright yellow-green lantern abdomen and sparkles',
     'Luciérnaga gigante que guía a los viajeros perdidos.',
     'A giant firefly that guides lost travelers.'),
    ('lumbrestrella', 'Lumbrestrella', 'luz/electrico', 2, None, 'epico', 'rapido', 'distancia', 'aurora', 'grande',
     'majestic star firefly creature with crystal wings, a radiant star-shaped lantern and electric light trails',
     'Su luz se ve desde el espacio. Dicen que es una estrella que bajó.',
     'Its light can be seen from space. They say it is a star that came down.'),
    ('rayuku', 'Rayuku', 'electrico/viento', 0, None, 'epico', 'rapido', 'distancia', 'furia_tormenta', 'grande',
     'thunderbird creature with wings made of storm clouds, lightning feathers and glowing yellow eyes',
     'Ave del trueno de los Andes. Sus alas traen las tormentas.',
     'The thunderbird of the Andes. Its wings bring the storms.'),
    ('rasuwawa', 'Rasuwawa', 'hielo', 1, 'rasuruna', 'epico', 'robusto', 'cuerpo', 'corazon_glaciar', 'mediano',
     'small yeti-like snow creature with fluffy white fur, an icy blue face and a woven Andean hat',
     'Wawa significa bebé. Este pequeño vive en la nieve eterna.',
     'Wawa means baby. This little one lives in the everlasting snow.'),
    ('rasuruna', 'Rasuruna', 'hielo/luz', 2, None, 'epico', 'robusto', 'cuerpo', 'corazon_glaciar', 'grande',
     'giant snow guardian creature with glacier ice armor shining in the sunlight, white fur, an Andean poncho and a glowing crystal staff',
     'Rasu es nieve y runa es gente: el guardián de los glaciares.',
     'Rasu means snow and runa means people: the guardian of the glaciers.'),
    ('jorobin', 'Jorobín', 'agua', 1, 'jorobalena', 'epico', 'tanque', 'distancia', 'marea', 'mediano',
     'cute baby humpback whale creature with long white flippers, a bumpy head and a happy water spout',
     'Ballenato que llega a Puerto López cada año.',
     'A whale calf that arrives at Puerto López every year.'),
    ('jorobalena', 'Jorobalena', 'agua/viento', 2, None, 'epico', 'tanque', 'distancia', 'marea', 'grande',
     'huge majestic humpback whale creature leaping, long flippers like wings, barnacles and a powerful blowhole spout',
     'Su canto se escucha a cientos de kilómetros. Salta como si volara.',
     'Its song can be heard hundreds of miles away. It leaps as if it could fly.'),
    ('sacharuna', 'Sacharuna', 'planta/roca', 0, None, 'epico', 'tanque', 'cuerpo', 'fotosintesis', 'grande',
     'ancient jungle giant creature made of trees, stones and roots, with a mossy face, glowing seeds and birds nesting on its shoulders',
     'El hombre de la selva. Cuida a los animales del bosque.',
     'The wild man of the jungle. It protects the forest animals.'),
    ('sangayon', 'Sangayón', 'fuego/roca', 0, None, 'epico', 'fuerte', 'cuerpo', 'brasa_interior', 'grande',
     'furious volcano beast creature with an always-erupting crater on its back, a black rock body and a constant ash cloud',
     'El volcán Sangay nunca descansa, y él tampoco.',
     'Sangay volcano never rests, and neither does it.'),
    ('chimbila', 'Chimbilá', 'sombra/viento', 0, None, 'epico', 'asesino', 'distancia', 'vampiro', 'mediano',
     'mysterious vampire bat creature with large purple membranous wings, glowing red eyes and a smoky shadow trail',
     'Murciélago de las cuevas de Jumandy. Solo sale con luna nueva.',
     'A bat from the Jumandy caves. It only comes out under a new moon.'),
    # ---- legendarios
    ('taitachimbo', 'Taitachimbo', 'roca/hielo', 0, None, 'legendario', 'tanque', 'cuerpo', 'taita', 'enorme',
     'colossal ancient mountain titan creature with a body like a snow-capped mountain, a glacier beard, wise glowing eyes and a stone crown, legendary',
     'Taita Chimborazo, el padre de las montañas. Su cumbre es el punto de la Tierra más cercano al sol.',
     "Taita Chimborazo, father of the mountains. Its summit is the point on Earth closest to the sun."),
    ('mamatungura', 'Mamatungura', 'fuego/roca', 0, None, 'legendario', 'fuerte', 'cuerpo', 'mama_volcan', 'enorme',
     'majestic legendary volcano goddess creature, a giant lava dragon with a flowing ash-cloud mane, molten gold veins and an erupting crown',
     'Mama Tungurahua, la volcana de fuego. Su enojo ilumina la noche.',
     'Mama Tungurahua, the mother volcano of fire. Her anger lights up the night.'),
    ('inti', 'Inti', 'luz/fuego', 0, None, 'legendario', 'equilibrado', 'distancia', 'sol_eterno', 'enorme',
     'radiant legendary sun god creature, a golden lion-like beast with a blazing sun disk mane of rays, ancient Andean gold ornaments and a fiery aura',
     'El dios Sol de los Andes. Cada junio se le celebra en el Inti Raymi.',
     'The Sun god of the Andes. Every June it is celebrated in the Inti Raymi.'),
    ('apukuntur', 'Apukuntur', 'viento/sombra', 0, None, 'legendario', 'asesino', 'distancia', 'rey_andes', 'enorme',
     'colossal legendary Andean condor king creature with enormous black wings with white edges, a white feather collar, a dark storm aura and a golden crown',
     'Apu Kuntur, el gran cóndor. Lleva las almas hasta lo alto de las montañas.',
     'Apu Kuntur, the great condor. It carries souls to the top of the mountains.'),
    ('cuichi', 'Cuichi', 'agua/luz', 0, None, 'legendario', 'rapido', 'distancia', 'arcoiris', 'enorme',
     'mythical legendary rainbow serpent creature with shimmering seven-color scales, water flowing around its long body and a glowing crystal horn',
     'El espíritu del arcoíris de los Andes. Aparece después de la lluvia.',
     'The rainbow spirit of the Andes. It appears after the rain.'),
]

assert len(R) == 100, len(R)
assert len({r[0] for r in R}) == 100

if __name__ == '__main__':
    rnd = random.Random(2026)
    out = {}
    for (cid, nombre, tipos, etapa, evo, rareza, perfil, basico, hab, talla, visual, es, en) in R:
        out[cid] = {'nombre': nombre, 'tipos': tipos.split('/'), 'etapa': etapa, 'evoluciona': evo, 'rareza': rareza, 'perfil': perfil,
                    'basico': basico, 'habilidad': hab, 'talla': talla, 'semilla': rnd.randint(1, 99999), 'visual': visual, 'desc': es, 'desc_en': en}
    path = os.path.join(os.path.dirname(__file__), '..', 'assets', 'criaturas', 'criaturas.json')
    json.dump(out, open(path, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    print('ok', len(out))
