// English text for game data. Spanish lives in data.ts / trainer.ts (it is the source of truth).
// Primal names are proper nouns and stay the same in both languages.

export const EN = {
  elementos: { fuego: 'Fire', agua: 'Water', planta: 'Grass', electrico: 'Electric', roca: 'Rock', viento: 'Wind', sombra: 'Shadow' } as Record<string, string>,
  movimientos: {
    ascuas: ['Embers', 'Three embers in a spread.'],
    llamarada: ['Flamethrower', 'A straight stream of fire.'],
    embestida_ignea: ['Flame Rush', 'Charges forward wreathed in flames.'],
    erupcion: ['Eruption', 'The ground ahead bursts into fire.'],
    burbuja: ['Bubble', 'A bubble that slows the target.'],
    hidrochorro: ['Hydro Jet', 'A high-pressure jet that pushes back.'],
    ola: ['Tidal Ring', 'A wave around you that pushes everyone away.'],
    marea_curativa: ['Healing Tide', 'Restores part of your health.'],
    hojas_navaja: ['Razor Leaves', 'Sharp leaves in a spread.'],
    esporas: ['Spores', 'A cloud of poisonous spores.'],
    latigo_cepa: ['Vine Lash', 'A long, fast whip.'],
    raices: ['Rootguard', 'Takes root: a sturdy shield.'],
    chispazo: ['Spark', 'A fast bolt that may paralyze.'],
    rayo_trueno: ['Thunderstrike', 'Lightning falls from the sky.'],
    carga_voltio: ['Volt Charge', 'A lightning-fast electric charge.'],
    aceleron: ['Overdrive', '+40% speed for a while.'],
    lanzarrocas: ['Rock Toss', 'A heavy, staggering boulder.'],
    terremoto: ['Earthquake', 'Shakes the ground around you.'],
    coraza: ['Stoneplate', 'A massive stone shield.'],
    avalancha: ['Rockslide', 'Rocks crash down on the target.'],
    cuchilla_aire: ['Air Blade', 'Slices through enemies.'],
    tornado: ['Tornado', 'A twister that slows.'],
    vuelo_raudo: ['Swift Dive', 'A long, low-flying dash.'],
    vendaval: ['Gale', 'A gust that blows everything away.'],
    bola_sombra: ['Shadow Orb', 'A sphere of darkness.'],
    paso_sombrio: ['Shadowstep', 'Passes through the rival, untouchable.'],
    maldicion: ['Hex', 'A cursed circle that poisons.'],
    aullido: ['Howl', '+35% damage for a while.'],
  } as Record<string, [string, string]>,
  habilidades: {
    brasa_interior: ['Inner Blaze', 'Below 35% health, its fire attacks deal +30% damage.'],
    marea: ['Torrent', 'Below 35% health, its water attacks deal +30% damage.'],
    espesura: ['Overgrowth', 'Below 35% health, its grass attacks deal +30% damage.'],
    estatica: ['Static', 'Its basic attacks may paralyze (15%).'],
    furia_tormenta: ['Storm Fury', '+12% damage and +10% speed.'],
    roca_solida: ['Solid Rock', 'Takes 15% less damage.'],
    viento_cola: ['Tailwind', 'Moves 20% faster.'],
    sombra_esquiva: ['Shadow Veil', '15% chance to dodge an attack.'],
  } as Record<string, [string, string]>,
  especies: {
    chispi: 'A restless salamander. Its crest burns brighter when it is happy.',
    llamarak: 'A warrior with a blazing mane. It never backs down.',
    infernox: 'A volcanic beast with magma running through its cracks.',
    gotin: 'A curious axolotl. The bubble on its tail never pops.',
    marejon: 'A warrior otter that bends water with its paws.',
    abisaurio: 'An armored serpent from the deep.',
    brotin: 'A leafy hedgehog. When startled, it blooms.',
    espinardo: 'A thorny boar with tusks of hardwood.',
    selvagor: 'An ancient beast with a tree growing on its back.',
    voltiron: 'A sparking ferret that never stands still.',
    tormentauro: 'A storm bull. Lightning strikes wherever it charges.',
    pedrusco: 'A stone crab that collects crystals.',
    golemon: 'A rock gorilla whose crystal fists split mountains.',
    cefiro: 'A wind falcon that flies faster than its own shadow.',
    umbraz: 'A shadow fox with tails of ghostly fire.',
  } as Record<string, string>,
  especiales: {
    supernova: ['Supernova', 'Bursts in a solar blast that burns everything around it.'],
    maremoto: ['Tsunami', 'Unleashes a colossal wave in a straight line.'],
    jardin_espinoso: ['Thorn Garden', 'Grows a field of poison thorns and restores health.'],
    tormenta: ['Tempest', 'Five lightning bolts chase the rival.'],
    meteoro: ['Meteor', 'A meteor falls from the sky and stuns on impact.'],
    huracan: ['Hurricane', 'Streaks across the arena and leaves a hurricane behind.'],
    eclipse: ['Eclipse', 'Vanishes, reappears behind the rival and strikes from behind.'],
  } as Record<string, [string, string]>,
  ligas: { bronce: 'Bronze League', plata: 'Silver League', oro: 'Gold League', platino: 'Platinum League', diamante: 'Diamond League', maestro: 'Master League', campeon: 'Champion League' } as Record<string, string>,
  medallas: {
    brasa: ['Ember Badge', 'Your first step as a Tamer.'],
    oleaje: ['Surge Badge', 'You know when to switch Primals.'],
    brote: ['Sprout Badge', 'Your team is starting to grow.'],
    voltio: ['Volt Badge', 'Lightning-fast reflexes.'],
    roca: ['Boulder Badge', 'Steady as a mountain.'],
    vendaval: ['Gale Badge', 'Nobody can keep up with you.'],
    umbral: ['Threshold Badge', 'You have mastered even the dark.'],
    primal: ['Primal Badge', 'A legend of the Primal League.'],
  } as Record<string, [string, string]>,
  habDomador: {
    entrenador: ['Natural Trainer', '+6% experience for your Primals per level.'],
    negociante: ['Dealmaker', '+8% coins per battle per level.'],
    vinculo: ['Bond', '+3% health for your whole team per level.'],
    relevo: ['Quick Swap', '-0.4 s Primal swap cooldown per level.'],
    instinto: ['Instinct', '-4% move cooldown per level.'],
    capturador: ['Catcher', '-8% capture cost per level.'],
  } as Record<string, [string, string]>,
};
