// English text for game data. Spanish lives in data.ts / trainer.ts (it is the source of truth).
// Primal names are proper nouns and stay the same in both languages.

import { ESPECIES_EN } from './especies_en';

export const EN = {
  elementos: { fuego: 'Fire', agua: 'Water', planta: 'Grass', electrico: 'Electric', roca: 'Rock', viento: 'Wind', sombra: 'Shadow', hielo: 'Ice', luz: 'Light' } as Record<string, string>,
  rarezas: { comun: 'Common', raro: 'Rare', epico: 'Epic', legendario: 'Legendary' } as Record<string, string>,
  movimientos: {
    ascuas: ['Embers', 'Three embers in a spread.'],
    bola_fuego: ['Fireball', 'A blazing ball that burns.'],
    llamarada: ['Flamethrower', 'A straight stream of fire.'],
    erupcion: ['Eruption', 'The ground ahead bursts into fire.'],
    embestida_ignea: ['Flame Rush', 'Charges forward wreathed in flames.'],
    ardor: ['Blaze Up', '+30% damage for a while.'],
    burbuja: ['Bubble', 'A bubble that slows the target.'],
    lanza_agua: ['Water Lance', 'A fast jet that pierces through.'],
    hidrochorro: ['Hydro Jet', 'A high-pressure jet that pushes back.'],
    torbellino: ['Whirlpool', 'A vortex that traps and slows.'],
    ola: ['Tidal Ring', 'A wave around you that pushes everyone away.'],
    marea_curativa: ['Healing Tide', 'Restores part of your health.'],
    hojas_navaja: ['Razor Leaves', 'Sharp leaves in a spread.'],
    semillas: ['Seed Shower', 'Five hard seeds in a spread.'],
    latigo_cepa: ['Vine Lash', 'A long, fast whip.'],
    esporas: ['Spores', 'A cloud of poisonous spores.'],
    rodillo_espinas: ['Thorn Roll', 'Rolls forward covered in poison thorns.'],
    raices: ['Rootguard', 'Takes root: a sturdy shield.'],
    chispazo: ['Spark', 'A fast bolt that may paralyze.'],
    bola_voltio: ['Volt Orb', 'A slow but powerful electric sphere.'],
    descarga: ['Discharge', 'An electric blast in a straight line.'],
    rayo_trueno: ['Thunderstrike', 'Lightning falls from the sky.'],
    carga_voltio: ['Volt Charge', 'A lightning-fast electric charge.'],
    aceleron: ['Overdrive', '+40% speed for a while.'],
    lanzarrocas: ['Rock Toss', 'A heavy boulder that knocks back.'],
    pedrada: ['Stone Volley', 'Three stones in a spread.'],
    grieta: ['Fissure', 'The ground splits in a line and spikes burst out.'],
    avalancha: ['Rockslide', 'Rocks crash down on the target.'],
    terremoto: ['Earthquake', 'Shakes the ground around you.'],
    coraza: ['Stoneplate', 'A massive stone shield.'],
    cuchilla_aire: ['Air Blade', 'Slices through enemies.'],
    pluma_filo: ['Razor Feathers', 'Three sharp feathers.'],
    corriente: ['Downdraft', 'A gale in a line that drags the rival.'],
    tornado: ['Tornado', 'A twister that slows.'],
    vuelo_raudo: ['Swift Dive', 'A long, low-flying dash.'],
    vendaval: ['Gale', 'A gust that blows everything away.'],
    bola_sombra: ['Shadow Orb', 'A sphere of darkness.'],
    colmillo_sombra: ['Shadow Fangs', 'Two dark fangs that poison.'],
    garra_eclipse: ['Eclipse Claw', 'A very long shadow slash.'],
    maldicion: ['Hex', 'A cursed circle that poisons.'],
    paso_sombrio: ['Shadowstep', 'Passes through the rival, untouchable.'],
    aullido: ['Howl', '+35% damage for a while.'],
    granizo: ['Hail', 'Three hailstones that may slow.'],
    carambano: ['Icicle', 'A piercing spike of ice.'],
    aliento_helado: ['Frost Breath', 'A freezing breath in a line.'],
    pico_glaciar: ['Glacier Spike', 'An ice spike bursts from the ground and freezes.'],
    patinazo: ['Ice Slide', 'Slides on ice and rams the rival.'],
    muro_hielo: ['Ice Wall', 'A shell of ice.'],
    destello: ['Flash', 'A fast beam of light.'],
    prisma: ['Prism', 'Five colored rays in a spread.'],
    rayo_solar: ['Solar Beam', 'Focuses sunlight into a long beam.'],
    juicio: ['Judgment', 'A pillar of light falls from the sky.'],
    saeta_luz: ['Light Arrow', 'Turns into light and passes through the rival.'],
    bendicion: ['Blessing', 'A warm light that heals.'],
  } as Record<string, [string, string]>,
  habilidades: {
    brasa_interior: ['Inner Blaze', 'Below 35% health, its fire attacks deal +30% damage.'],
    marea: ['Torrent', 'Below 35% health, its water attacks deal +30% damage.'],
    espesura: ['Overgrowth', 'Below 35% health, its grass attacks deal +30% damage.'],
    corazon_glaciar: ['Glacier Heart', 'Below 35% health, its ice attacks deal +30% damage.'],
    aurora: ['Aurora', 'Below 35% health, its light attacks deal +30% damage.'],
    estatica: ['Static', 'Its basic attacks may paralyze (15%).'],
    escarcha: ['Frostbite', 'Its basic attacks may slow (25%).'],
    toxico: ['Toxic Skin', 'Its basic attacks may poison (20%).'],
    furia_tormenta: ['Storm Fury', '+12% damage and +10% speed.'],
    roca_solida: ['Solid Rock', 'Takes 15% less damage.'],
    viento_cola: ['Tailwind', 'Moves 20% faster.'],
    sombra_esquiva: ['Shadow Veil', '15% chance to dodge an attack.'],
    fotosintesis: ['Photosynthesis', 'Recovers 1.5% health every 2 seconds.'],
    vampiro: ['Vampire', 'Heals 12% of the damage it deals.'],
    concentracion: ['Focus', 'Charges its special 35% faster.'],
    instinto_cazador: ['Hunter Instinct', 'Double critical hit chance.'],
    taita: ['Father of Mountains', 'Takes 25% less damage.'],
    mama_volcan: ['Volcano Mother', 'Its basic attacks burn (25%) and at low health its fire hits +30%.'],
    sol_eterno: ['Eternal Sun', '+10% damage and recovers 1% health every 2 seconds.'],
    rey_andes: ['King of the Andes', '+15% speed and 18% critical hit chance.'],
    arcoiris: ['Rainbow Spirit', 'Charges its special 40% faster and dodges 10% of attacks.'],
  } as Record<string, [string, string]>,
  especies: ESPECIES_EN,
  especiales: {
    supernova: ['Supernova', 'Pulls the rival in, explodes like a sun and sends out a ring of fire pillars that leave the ground burning.'],
    maremoto: ['Tsunami', 'Three colossal waves sweep in a fan and leave a whirlpool that traps the rival.'],
    jardin_espinoso: ['Thorn Garden', 'Thorns burst in a line toward the rival, a poison field blooms and it restores health.'],
    tormenta: ['Tempest', 'The sky darkens: six lightning bolts chase the rival and the last one paralyzes.'],
    meteoro: ['Meteor Shower', 'Meteors rain around the rival, then a giant one stuns it.'],
    huracan: ['Hurricane', 'Streaks across the arena and leaves a hurricane that sucks the rival in.'],
    eclipse: ['Eclipse', 'The arena goes dark, it reappears behind the rival and strikes three times.'],
    ventisca_glacial: ['Glacial Blizzard', 'Three waves of ice spikes zigzag forward and leave the ground frozen.'],
    prisma_solar: ['Solar Prism', 'Fires seven beams of light in a star, then a huge one at the rival.'],
    avalancha_andina: ['Andean Avalanche', 'Seven snowy boulders roll down toward the rival.'],
    corona_nevada: ['Snow Crown', 'A ring of ice spikes surrounds it, freezes and grants a huge shield.'],
    furia_volcanica: ['Volcanic Fury', 'Hurls seven lava bombs that leave burning pools.'],
    rio_de_lava: ['Lava River', 'Opens a straight river of lava that burns whoever crosses it.'],
    sol_naciente: ['Rising Sun', 'Two rings of sunlight burst around it and it recovers 25% health.'],
    rayo_de_inti: ["Inti's Ray", 'The whole sun in a giant beam across the arena.'],
    vuelo_del_condor: ["Condor's Flight", 'Soars out of reach and dives onto the rival.'],
    alas_de_tormenta: ['Storm Wings', 'Twelve dark feathers in every direction and a vortex that pulls the rival.'],
    arcoiris: ['Rainbow', 'Seven colored beams sweep the arena one after another.'],
    diluvio: ['Deluge', 'A downpour falls on the rival, slowing and wearing it down, and heals Cuichi.'],
  } as Record<string, [string, string]>,
  ligas: { bronce: 'Bronze League', plata: 'Silver League', oro: 'Gold League', platino: 'Platinum League', diamante: 'Diamond League', maestro: 'Master League', campeon: 'Champion League' } as Record<string, string>,
  arenas: {
    bronce: 'Malecón Stadium', plata: 'Amazon Coliseum', oro: 'Cotopaxi Arena', platino: 'Galápagos Stadium',
    diamante: 'Colonial Quito Plaza', maestro: 'Chimborazo Glacier', campeon: 'Middle of the World',
  } as Record<string, string>,
  medallas: {
    brasa: ['Ember Badge', 'Your first step as a Trainer.'],
    oleaje: ['Surge Badge', 'You know when to switch Primals.'],
    brote: ['Sprout Badge', 'Your team is starting to grow.'],
    voltio: ['Volt Badge', 'Lightning-fast reflexes.'],
    roca: ['Boulder Badge', 'Steady as a mountain.'],
    vendaval: ['Gale Badge', 'Nobody can keep up with you.'],
    umbral: ['Threshold Badge', 'You have mastered even the dark.'],
    primal: ['Primal Badge', 'A legend of the Primal League.'],
  } as Record<string, [string, string]>,
  misiones: {
    ganar: 'Win {n} League battles', jugar: 'Play {n} League battles', especial: 'Unleash {n} specials', ko: 'Defeat {n} rival Primals',
    combo: 'Land a 15-hit combo', captura: 'Catch a Primal', amistosa: 'Play a friendly battle',
  } as Record<string, string>,
  habDomador: {
    entrenador: ['Natural Trainer', '+6% experience for your Primals per level.'],
    negociante: ['Dealmaker', '+8% coins per battle per level.'],
    vinculo: ['Bond', '+3% health for your whole team per level.'],
    relevo: ['Quick Swap', '-0.4 s Primal swap cooldown per level.'],
    instinto: ['Instinct', '-4% move cooldown per level.'],
    capturador: ['Catcher', '-8% capture cost per level.'],
  } as Record<string, [string, string]>,
};
