// GENERADO por scripts/construir_especies.py. Descripciones en inglés de cada Primal.
export const ESPECIES_EN: Record<string, string> = {
 "tunguri": "A salamander born on the slopes of Tungurahua. The tiny crater on its back smokes when it gets excited.",
 "tungurak": "It spits ash when angry. Its footsteps leave glowing embers.",
 "tungurex": "King of the Andean volcanoes. When it roars, the whole land rumbles.",
 "yakupi": "A Galápagos sea lion pup. It plays with the waves all day long.",
 "yakulobo": "It swims faster than a speedboat and fires jets from its flippers.",
 "yakuaron": "Guardian of the cold Humboldt Current. Its tusks are made of everlasting ice.",
 "cacaito": "Born from a fine-aroma cacao pod. It smells like chocolate.",
 "cacaoso": "It protects the coastal plantations and hurls bitter seeds.",
 "cacaotor": "Its body is made of dark cacao. They say one bite gives strength for a whole day.",
 "chispez": "A little Amazon fish that sparks when it laughs.",
 "anguilampo": "It lights up the rivers at night. Its shock scares off any predator.",
 "voltanguila": "Mistress of the Napo River storms. Its roar sounds like thunder.",
 "quindito": "Quindes are Ecuador's hummingbirds. This one never stops buzzing.",
 "quindazo": "Its beak is as sharp as a sword. It flies backwards to dodge.",
 "quindestral": "Inspired by the Chimborazo hillstar, an Andean hummingbird. Its wings leave trails of light.",
 "galapito": "A tiny Galápagos tortoise. It can sleep for a hundred years straight.",
 "galapon": "Its shell withstands an avalanche. It walks slowly but never stops.",
 "galapagon": "So big that islands grow on its shell. It is the grandfather of the archipelago.",
 "chusik": "Chusik means owl in Kichwa. Its eyes see in total darkness.",
 "chusikar": "It hunts without a sound. They say it carries messages from the night.",
 "chusikron": "When it opens its wings, day turns into night.",
 "ukumarito": "A spectacled bear cub from the páramo. It loves snow.",
 "ukumari": "Ukumari is the bear of Andean legends. Its claws freeze whatever they touch.",
 "ukumarasu": "It sleeps beneath the glaciers. Its awakening triggers avalanches.",
 "morfito": "An Amazonian caterpillar that glows in the dark.",
 "crisalux": "Inside its chrysalis it keeps the light of the sun.",
 "morfolux": "The largest blue morpho of the Amazon. Its wings are dazzling.",
 "llamin": "A little llama with a flame. Its wool is always warm.",
 "llamaradon": "It spits fire instead of saliva and runs across the Andes like the wind.",
 "dardin": "A tiny poison frog of the forest. Its colors warn: don't touch me!",
 "dardosa": "Its skin has enough venom to put a jaguar to sleep.",
 "pinzin": "It lives among the mangrove roots and pinches anyone who gets close.",
 "pinzaglar": "Its claws split logs. It defends the mangrove like a fortress.",
 "piranin": "Small but very bitey. It never travels alone.",
 "piranazo": "It smells fear from afar. Its bite pierces armor.",
 "capibin": "The calmest Primal in the river. Everyone wants to be its friend.",
 "capibaron": "It swims at its own pace and never loses its cool. Even birds rest on it.",
 "pelusin": "A shy fuzzy tarantula. It weaves star-shaped webs.",
 "taranton": "It lives in Amazon caves. Its legs are as hard as stone.",
 "piquerito": "It shows off its blue feet and dances to make friends.",
 "patazul": "It dives into the sea like an arrow. Its dance is famous in Galápagos.",
 "iguanin": "It sunbathes on volcanic rocks until it glows.",
 "iguanarca": "It eats cactus and breathes fire. It rules the dry islands.",
 "frailito": "A small páramo plant covered in fuzz so it never gets cold.",
 "frailejon": "Guardian of the páramo's water. It catches the mist and turns it into rivers.",
 "aullin": "Its howl can be heard for miles. Howling charges it with electricity.",
 "aullatrueno": "When it howls, the rain begins. It owns the treetops.",
 "tucanin": "Its beak weighs almost nothing, even though it looks huge.",
 "tucanazo": "Its beak burns with the colors of the Amazon sunset.",
 "otoronguito": "A cub of the otorongo, the Amazon jaguar. It plays at hunting shadows.",
 "otorongo": "King of the jungle. It appears and vanishes among the leaves.",
 "amaruto": "Amaru is the sacred serpent of the Andes. This one is still small.",
 "amarusacha": "The largest anaconda in the river. It holds the jungle on its back.",
 "bufeito": "A pink Amazon river dolphin. It loves doing flips.",
 "bufeorosa": "Legend says that at night it turns into a person and goes to parties.",
 "harpin": "A harpy eagle chick. It already has a hunter's stare.",
 "harpiandina": "The strongest bird of the forest. Its talons are like hooks.",
 "pingui": "One of the few penguins that live on the Equator.",
 "galapingo": "It skates over the sea, freezing the waves as it goes.",
 "martillin": "A baby hammerhead shark. It bumps its head on everything, but it doesn't hurt.",
 "martillazo": "It patrols the waters of Galápagos. Its head smashes rocks.",
 "atuk": "Atuk means fox in Kichwa. It is mischievous and very clever.",
 "atukrasu": "The ghost fox of the páramo. It leaves frosty footprints.",
 "pumita": "A puma cub that plays among the rocks.",
 "pumarumi": "Rumi means stone. Its armor recalls the Inca walls.",
 "tapirin": "A mountain tapir calf. Its stripes fade as it grows.",
 "tapiramo": "It plants the cloud forest with every step.",
 "vicunin": "Its wool is the finest in the world.",
 "vicunieve": "It runs along the slopes of Chimborazo as fast as the wind.",
 "fragatin": "It puffs up its red pouch to show off.",
 "fragatormenta": "It steals food from other birds in mid-flight, and lightning too.",
 "cuernin": "A beetle larva. It is already super strong.",
 "hercularmor": "It lifts a hundred times its weight. Its horn conducts electricity.",
 "cristalin": "A glass frog: you can see its heart glowing.",
 "ranacristal": "Its crystal body splits light like a prism.",
 "caimancito": "A black caiman hatchling. It hides with only its eyes above the water.",
 "caimanegro": "The great hunter of the Amazon lagoons.",
 "ayahuma": "The spirit of the Inti Raymi dance. It has two faces: one looks to the past, the other to the future.",
 "cotopaxin": "A little volcano wearing a snow cap. It boils inside.",
 "cotopaxor": "The most famous snowy volcano comes to life. Fire and ice in a single body.",
 "quiloton": "It sleeps at the bottom of the Quilotoa lagoon. Its color changes with the sun.",
 "tunda": "A spirit from the legends of Esmeraldas. It confuses anyone lost in the forest.",
 "gallofierro": "The iron rooster of Cuenca's cathedral. When it crows, the sun rises.",
 "iguamarina": "A marine iguana that sneezes salt. It dives among corals.",
 "draconarina": "Half dragon, half marine iguana. It makes the sea boil.",
 "lumbron": "A giant firefly that guides lost travelers.",
 "lumbrestrella": "Its light can be seen from space. They say it is a star that came down.",
 "rayuku": "The thunderbird of the Andes. Its wings bring the storms.",
 "rasuwawa": "Wawa means baby. This little one lives in the everlasting snow.",
 "rasuruna": "Rasu means snow and runa means people: the guardian of the glaciers.",
 "jorobin": "A whale calf that arrives at Puerto López every year.",
 "jorobalena": "Its song can be heard hundreds of miles away. It leaps as if it could fly.",
 "sacharuna": "The wild man of the jungle. It protects the forest animals.",
 "sangayon": "Sangay volcano never rests, and neither does it.",
 "chimbila": "A bat from the Jumandy caves. It only comes out under a new moon.",
 "taitachimbo": "Taita Chimborazo, father of the mountains. Its summit is the point on Earth closest to the sun.",
 "mamatungura": "Mama Tungurahua, the mother volcano of fire. Her anger lights up the night.",
 "inti": "The Sun god of the Andes. Every June it is celebrated in the Inti Raymi.",
 "apukuntur": "Apu Kuntur, the great condor. It carries souls to the top of the mountains.",
 "cuichi": "The rainbow spirit of the Andes. It appears after the rain."
};
